from __future__ import annotations

import re
from pathlib import Path

from docx import Document
from docx.document import Document as DocumentType
from docx.oxml.table import CT_Tbl
from docx.oxml.text.paragraph import CT_P
from docx.table import Table
from docx.text.paragraph import Paragraph


SOURCE_DOCX = Path("/Users/rafalaffeier/projects/asistente/documentos/AI_Assistant_Architecture_Professiona.docx")
OUTPUT_MD = Path("docs/architecture-reference.md")


def iter_blocks(parent: DocumentType):
    body = parent.element.body
    for child in body.iterchildren():
        if isinstance(child, CT_P):
            yield Paragraph(child, parent)
        elif isinstance(child, CT_Tbl):
            yield Table(child, parent)


def clean_cell(text: str) -> str:
    text = re.sub(r"\s+", " ", text.strip())
    return text.replace("|", "\\|")


def table_to_markdown(table: Table) -> list[str]:
    rows = [[clean_cell(cell.text) for cell in row.cells] for row in table.rows]
    rows = [row for row in rows if any(cell for cell in row)]
    if not rows:
        return []

    width = max(len(row) for row in rows)
    normalized = [row + [""] * (width - len(row)) for row in rows]
    header = normalized[0]
    separator = ["---"] * width
    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(separator) + " |",
    ]
    for row in normalized[1:]:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def paragraph_to_markdown(paragraph: Paragraph) -> str:
    text = paragraph.text.strip()
    if not text:
        return ""

    style = paragraph.style.name if paragraph.style is not None else ""
    heading_match = re.fullmatch(r"Heading ([1-6])", style or "")
    if heading_match:
        level = int(heading_match.group(1))
        return f"{'#' * level} {text}"

    return text


def main() -> None:
    document = Document(SOURCE_DOCX)
    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "<!--",
        "Source: /Users/rafalaffeier/projects/asistente/documentos/AI_Assistant_Architecture_Professiona.docx",
        "Generated by scripts/docx_to_markdown.py. Edit this Markdown as the working architecture reference.",
        "The Word document remains the human-friendly formatted copy.",
        "-->",
        "",
    ]

    for block in iter_blocks(document):
        if isinstance(block, Paragraph):
            rendered = paragraph_to_markdown(block)
            if rendered:
                lines.append(rendered)
                lines.append("")
        elif isinstance(block, Table):
            rendered_table = table_to_markdown(block)
            if rendered_table:
                lines.extend(rendered_table)
                lines.append("")

    OUTPUT_MD.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
